window.OW_DATA = [
    {
      "FIELD1": "counter-header",
      "ANA": "same-hero",
      "ASHE": "counter-good counter-medium",
      "BAPTISTE": "",
      "BASTION": "counter-good counter-medium",
      "BRIGITTE": "",
      "D.VA": "counter-bad counter-medium",
      "DOOMFIST": "",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "counter-good counter-medium",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "counter-good counter-medium",
      "ORISA": "",
      "PHARAH": "counter-good counter-medium",
      "REAPER": "counter-good counter-medium",
      "REINHARDT": "",
      "ROADHOG": "",
      "SIGMA": "counter-bad counter-medium",
      "SOLDIER: 76": "",
      "SOMBRA": "counter-bad counter-medium",
      "SYMMETRA": "",
      "TORBJORN": "counter-good counter-medium",
      "TRACER": "",
      "WIDOWMAKER": "",
      "WINSTON": "counter-bad counter-medium",
      "WRECKINGBALL": "counter-good counter-medium",
      "ZARYA": "",
      "ZENYATTA": "counter-good counter-medium"
    },
    {
      "FIELD1": "counter-header",
      "ANA": "counter-bad counter-medium",
      "ASHE": "same-hero",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "counter-good counter-medium",
      "D.VA": "counter-bad counter-medium",
      "DOOMFIST": "counter-good counter-medium",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "counter-good counter-medium",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "counter-good counter-medium",
      "MERCY": "counter-good counter-medium",
      "MOIRA": "",
      "ORISA": "counter-bad counter-medium",
      "PHARAH": "counter-good counter-strong",
      "REAPER": "counter-good counter-medium",
      "REINHARDT": "",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "counter-good counter-medium",
      "SOMBRA": "",
      "SYMMETRA": "counter-good counter-medium",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "counter-bad counter-medium",
      "WINSTON": "counter-bad counter-medium",
      "WRECKINGBALL": "counter-bad counter-medium",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "",
      "BAPTISTE": "same-hero counter-good counter-medium",
      "BASTION": "",
      "BRIGITTE": "",
      "D.VA": "",
      "DOOMFIST": "",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "",
      "REAPER": "",
      "REINHARDT": "",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "counter-bad counter-medium",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "same-hero",
      "BRIGITTE": "",
      "D.VA": "counter-bad counter-medium",
      "DOOMFIST": "",
      "GENJI": "counter-bad counter-medium",
      "HANZO": "counter-bad counter-medium",
      "JUNKRAT": "counter-bad counter-medium",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "",
      "REAPER": "",
      "REINHARDT": "counter-good counter-strong",
      "ROADHOG": "counter-bad counter-medium",
      "SIGMA": "",
      "SOLDIER: 76": "counter-bad counter-medium",
      "SOMBRA": "",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "counter-bad counter-medium",
      "WIDOWMAKER": "counter-bad counter-medium",
      "WINSTON": "counter-good counter-strong",
      "WRECKINGBALL": "",
      "ZARYA": "counter-good counter-medium",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "counter-bad counter-medium",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "same-hero",
      "D.VA": "counter-good counter-medium",
      "DOOMFIST": "",
      "GENJI": "counter-good counter-medium",
      "HANZO": "",
      "JUNKRAT": "counter-bad counter-medium",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "counter-bad counter-strong",
      "REAPER": "counter-bad counter-medium",
      "REINHARDT": "counter-good counter-medium",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "counter-bad counter-medium",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "counter-good counter-medium",
      "WIDOWMAKER": "",
      "WINSTON": "",
      "WRECKINGBALL": "counter-good counter-strong",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "counter-good counter-medium",
      "ASHE": "counter-good counter-medium",
      "BAPTISTE": "",
      "BASTION": "counter-good counter-medium",
      "BRIGITTE": "counter-bad counter-medium",
      "D.VA": "same-hero",
      "DOOMFIST": "counter-bad counter-medium",
      "GENJI": "",
      "HANZO": "counter-good counter-strong",
      "JUNKRAT": "counter-bad counter-medium",
      "LUCIO": "",
      "MCCREE": "counter-good counter-medium",
      "MEI": "counter-bad counter-medium",
      "MERCY": "counter-good counter-strong",
      "MOIRA": "counter-good counter-medium",
      "ORISA": "",
      "PHARAH": "counter-good counter-medium",
      "REAPER": "counter-bad counter-medium",
      "REINHARDT": "",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "counter-bad counter-medium",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "counter-good counter-strong",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "counter-bad counter-strong",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "counter-bad counter-medium",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "",
      "D.VA": "counter-good counter-medium",
      "DOOMFIST": "same-hero",
      "GENJI": "counter-good counter-medium",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "",
      "MCCREE": "counter-bad counter-medium",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "counter-bad counter-medium",
      "PHARAH": "counter-bad counter-strong",
      "REAPER": "",
      "REINHARDT": "counter-good counter-medium",
      "ROADHOG": "",
      "SIGMA": "counter-good counter-medium",
      "SOLDIER: 76": "counter-bad counter-medium",
      "SOMBRA": "counter-bad counter-strong",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "counter-good counter-medium",
      "BRIGITTE": "counter-bad counter-medium",
      "D.VA": "",
      "DOOMFIST": "counter-bad counter-medium",
      "GENJI": "same-hero",
      "HANZO": "counter-good counter-strong",
      "JUNKRAT": "",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "counter-good counter-strong",
      "MOIRA": "",
      "ORISA": "counter-good counter-medium",
      "PHARAH": "counter-bad counter-medium",
      "REAPER": "",
      "REINHARDT": "",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "counter-good counter-strong",
      "WINSTON": "counter-bad counter-strong",
      "WRECKINGBALL": "",
      "ZARYA": "counter-bad counter-strong",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "counter-bad counter-medium",
      "BAPTISTE": "",
      "BASTION": "counter-good counter-medium",
      "BRIGITTE": "",
      "D.VA": "counter-bad counter-strong",
      "DOOMFIST": "",
      "GENJI": "counter-bad counter-strong",
      "HANZO": "same-hero",
      "JUNKRAT": "",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "counter-good counter-medium",
      "PHARAH": "",
      "REAPER": "",
      "REINHARDT": "",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "counter-good counter-medium",
      "SYMMETRA": "",
      "TORBJORN": "counter-good counter-strong",
      "TRACER": "counter-bad counter-strong",
      "WIDOWMAKER": "counter-bad counter-medium",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "counter-good counter-medium",
      "BRIGITTE": "counter-good counter-medium",
      "D.VA": "counter-good counter-medium",
      "DOOMFIST": "",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "same-hero",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "counter-bad counter-strong",
      "REAPER": "counter-good counter-medium",
      "REINHARDT": "counter-good counter-strong",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "counter-good counter-medium",
      "SYMMETRA": "",
      "TORBJORN": "counter-good counter-strong",
      "TRACER": "counter-good counter-medium",
      "WIDOWMAKER": "counter-bad counter-strong",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "counter-bad counter-medium",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "counter-bad counter-medium",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "",
      "D.VA": "",
      "DOOMFIST": "",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "same-hero",
      "MCCREE": "counter-bad counter-strong",
      "MEI": "counter-good counter-medium",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "",
      "REAPER": "",
      "REINHARDT": "",
      "ROADHOG": "counter-bad counter-medium",
      "SIGMA": "counter-good counter-medium",
      "SOLDIER: 76": "",
      "SOMBRA": "counter-bad counter-medium",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "",
      "D.VA": "counter-bad counter-medium",
      "DOOMFIST": "counter-good counter-medium",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "counter-good counter-strong",
      "MCCREE": "same-hero",
      "MEI": "counter-bad counter-medium",
      "MERCY": "counter-good counter-medium",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "counter-good counter-strong",
      "REAPER": "",
      "REINHARDT": "",
      "ROADHOG": "counter-bad counter-medium",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "counter-good counter-medium",
      "SYMMETRA": "counter-good counter-medium",
      "TORBJORN": "",
      "TRACER": "counter-good counter-strong",
      "WIDOWMAKER": "counter-bad counter-medium",
      "WINSTON": "counter-bad counter-medium",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "counter-bad counter-medium",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "",
      "D.VA": "counter-good counter-medium",
      "DOOMFIST": "",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "counter-bad counter-medium",
      "MCCREE": "counter-good counter-medium",
      "MEI": "same-hero",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "counter-bad counter-medium",
      "REAPER": "",
      "REINHARDT": "counter-good counter-strong",
      "ROADHOG": "counter-good counter-strong",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "counter-bad counter-medium",
      "WINSTON": "",
      "WRECKINGBALL": "counter-good counter-medium",
      "ZARYA": "counter-bad counter-medium",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "counter-bad counter-medium",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "",
      "D.VA": "counter-bad counter-strong",
      "DOOMFIST": "",
      "GENJI": "counter-bad counter-strong",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "",
      "MCCREE": "counter-bad counter-medium",
      "MEI": "",
      "MERCY": "same-hero",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "",
      "REAPER": "",
      "REINHARDT": "",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "counter-bad counter-medium",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "",
      "D.VA": "counter-bad counter-medium",
      "DOOMFIST": "",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "same-hero",
      "ORISA": "counter-good counter-medium",
      "PHARAH": "",
      "REAPER": "",
      "REINHARDT": "counter-good counter-medium",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "counter-good counter-medium",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "",
      "D.VA": "",
      "DOOMFIST": "counter-good counter-medium",
      "GENJI": "counter-bad counter-medium",
      "HANZO": "counter-bad counter-medium",
      "JUNKRAT": "",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "counter-bad counter-medium",
      "ORISA": "same-hero",
      "PHARAH": "",
      "REAPER": "counter-bad counter-medium",
      "REINHARDT": "",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "",
      "SYMMETRA": "",
      "TORBJORN": "counter-good counter-medium",
      "TRACER": "",
      "WIDOWMAKER": "counter-good counter-medium",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "counter-bad counter-medium",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "counter-good counter-strong",
      "D.VA": "counter-bad counter-medium",
      "DOOMFIST": "counter-good counter-strong",
      "GENJI": "counter-good counter-medium",
      "HANZO": "",
      "JUNKRAT": "counter-good counter-strong",
      "LUCIO": "",
      "MCCREE": "counter-bad counter-strong",
      "MEI": "counter-good counter-medium",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "same-hero",
      "REAPER": "counter-good counter-strong",
      "REINHARDT": "counter-good counter-strong",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "counter-bad counter-medium",
      "SOMBRA": "",
      "SYMMETRA": "counter-good counter-strong",
      "TORBJORN": "",
      "TRACER": "counter-good counter-medium",
      "WIDOWMAKER": "counter-bad counter-strong",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "counter-good counter-strong",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "counter-bad counter-medium",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "",
      "D.VA": "counter-good counter-medium",
      "DOOMFIST": "",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "counter-bad counter-medium",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "counter-good counter-medium",
      "PHARAH": "counter-bad counter-strong",
      "REAPER": "same-hero",
      "REINHARDT": "counter-good counter-strong",
      "ROADHOG": "counter-good counter-strong",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "counter-good counter-medium",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "",
      "WINSTON": "counter-good counter-strong",
      "WRECKINGBALL": "counter-good counter-medium",
      "ZARYA": "counter-good counter-medium",
      "ZENYATTA": "counter-good counter-strong"
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "counter-bad counter-strong",
      "BRIGITTE": "counter-bad counter-medium",
      "D.VA": "",
      "DOOMFIST": "counter-bad counter-medium",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "counter-bad counter-strong",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "counter-bad counter-strong",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "counter-bad counter-medium",
      "PHARAH": "counter-bad counter-strong",
      "REAPER": "counter-bad counter-strong",
      "REINHARDT": "same-hero",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "counter-good counter-medium",
      "SOMBRA": "counter-bad counter-medium",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "counter-good counter-medium",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "counter-good counter-medium",
      "BRIGITTE": "",
      "D.VA": "",
      "DOOMFIST": "",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "counter-good counter-medium",
      "MCCREE": "counter-good counter-medium",
      "MEI": "counter-bad counter-strong",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "",
      "REAPER": "counter-bad counter-strong",
      "REINHARDT": "",
      "ROADHOG": "same-hero",
      "SIGMA": "counter-bad counter-medium",
      "SOLDIER: 76": "counter-good counter-medium",
      "SOMBRA": "counter-good counter-medium",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "counter-good counter-medium",
      "WINSTON": "counter-good counter-strong",
      "WRECKINGBALL": "counter-good counter-medium",
      "ZARYA": "counter-bad counter-medium",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "counter-good counter-medium",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "",
      "D.VA": "",
      "DOOMFIST": "counter-bad counter-medium",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "counter-bad counter-medium",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "",
      "REAPER": "",
      "REINHARDT": "",
      "ROADHOG": "counter-good counter-medium",
      "SIGMA": "same-hero",
      "SOLDIER: 76": "",
      "SOMBRA": "",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "counter-good counter-medium",
      "BRIGITTE": "",
      "D.VA": "",
      "DOOMFIST": "counter-good counter-medium",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "counter-good counter-medium",
      "REAPER": "",
      "REINHARDT": "counter-bad counter-medium",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "same-hero",
      "SOMBRA": "",
      "SYMMETRA": "",
      "TORBJORN": "counter-good counter-strong",
      "TRACER": "",
      "WIDOWMAKER": "",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "counter-good counter-medium",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "counter-good counter-medium",
      "D.VA": "counter-good counter-medium",
      "DOOMFIST": "counter-good counter-strong",
      "GENJI": "",
      "HANZO": "counter-bad counter-medium",
      "JUNKRAT": "counter-bad counter-medium",
      "LUCIO": "counter-good counter-medium",
      "MCCREE": "counter-bad counter-medium",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "",
      "REAPER": "counter-bad counter-medium",
      "REINHARDT": "counter-good counter-medium",
      "ROADHOG": "counter-bad counter-medium",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "same-hero",
      "SYMMETRA": "counter-good counter-medium",
      "TORBJORN": "",
      "TRACER": "counter-good counter-strong",
      "WIDOWMAKER": "",
      "WINSTON": "",
      "WRECKINGBALL": "counter-good counter-strong",
      "ZARYA": "",
      "ZENYATTA": "counter-good counter-medium"
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "",
      "D.VA": "",
      "DOOMFIST": "",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "",
      "MCCREE": "counter-bad counter-medium",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "counter-bad counter-strong",
      "REAPER": "",
      "REINHARDT": "",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "counter-bad counter-medium",
      "SYMMETRA": "same-hero",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "",
      "WINSTON": "counter-bad counter-strong",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "counter-bad counter-medium",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "",
      "D.VA": "",
      "DOOMFIST": "",
      "GENJI": "",
      "HANZO": "counter-bad counter-strong",
      "JUNKRAT": "counter-bad counter-strong",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "counter-bad counter-medium",
      "PHARAH": "",
      "REAPER": "",
      "REINHARDT": "",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "counter-bad counter-strong",
      "SOMBRA": "",
      "SYMMETRA": "",
      "TORBJORN": "same-hero",
      "TRACER": "counter-good counter-medium",
      "WIDOWMAKER": "counter-bad counter-strong",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "counter-bad counter-strong",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "counter-good counter-medium",
      "BRIGITTE": "counter-bad counter-medium",
      "D.VA": "",
      "DOOMFIST": "",
      "GENJI": "",
      "HANZO": "counter-good counter-strong",
      "JUNKRAT": "counter-bad counter-medium",
      "LUCIO": "",
      "MCCREE": "counter-bad counter-strong",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "counter-bad counter-medium",
      "REAPER": "",
      "REINHARDT": "",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "counter-bad counter-strong",
      "SYMMETRA": "",
      "TORBJORN": "counter-bad counter-medium",
      "TRACER": "same-hero",
      "WIDOWMAKER": "",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": "counter-good counter-strong"
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "counter-good counter-medium",
      "BRIGITTE": "",
      "D.VA": "counter-bad counter-strong",
      "DOOMFIST": "",
      "GENJI": "counter-bad counter-strong",
      "HANZO": "counter-good counter-medium",
      "JUNKRAT": "counter-good counter-strong",
      "LUCIO": "",
      "MCCREE": "counter-good counter-medium",
      "MEI": "counter-good counter-medium",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "counter-bad counter-medium",
      "PHARAH": "counter-good counter-strong",
      "REAPER": "",
      "REINHARDT": "counter-bad counter-medium",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "",
      "SYMMETRA": "",
      "TORBJORN": "counter-good counter-strong",
      "TRACER": "",
      "WIDOWMAKER": "same-hero",
      "WINSTON": "counter-bad counter-strong",
      "WRECKINGBALL": "counter-bad counter-medium",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "counter-good counter-medium",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "counter-bad counter-strong",
      "BRIGITTE": "",
      "D.VA": "",
      "DOOMFIST": "",
      "GENJI": "counter-good counter-strong",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "",
      "MCCREE": "counter-good counter-medium",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "",
      "REAPER": "counter-bad counter-strong",
      "REINHARDT": "",
      "ROADHOG": "counter-bad counter-strong",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "",
      "SYMMETRA": "counter-good counter-strong",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "counter-good counter-strong",
      "WINSTON": "same-hero",
      "WRECKINGBALL": "",
      "ZARYA": "",
      "ZENYATTA": "counter-good counter-strong"
    },
    {
      "FIELD1": "counter-header",
      "ANA": "counter-bad counter-medium",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "counter-bad counter-strong",
      "D.VA": "",
      "DOOMFIST": "",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "counter-bad counter-medium",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "",
      "REAPER": "counter-bad counter-medium",
      "REINHARDT": "",
      "ROADHOG": "counter-bad counter-medium",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "counter-bad counter-strong",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "",
      "WIDOWMAKER": "counter-good counter-medium",
      "WINSTON": "",
      "WRECKINGBALL": "same-hero",
      "ZARYA": "",
      "ZENYATTA": ""
    },
    {
      "FIELD1": "counter-header",
      "ANA": "",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "counter-bad counter-medium",
      "BRIGITTE": "",
      "D.VA": "counter-good counter-strong",
      "DOOMFIST": "",
      "GENJI": "counter-good counter-strong",
      "HANZO": "",
      "JUNKRAT": "counter-good counter-medium",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "counter-good counter-medium",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "counter-bad counter-strong",
      "REAPER": "counter-bad counter-medium",
      "REINHARDT": "",
      "ROADHOG": "counter-good counter-medium",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "",
      "SYMMETRA": "",
      "TORBJORN": "counter-good counter-strong",
      "TRACER": "",
      "WIDOWMAKER": "",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "same-hero",
      "ZENYATTA": "counter-bad counter-medium"
    },
    {
      "FIELD1": "counter-header",
      "ANA": "counter-bad counter-medium",
      "ASHE": "",
      "BAPTISTE": "",
      "BASTION": "",
      "BRIGITTE": "",
      "D.VA": "",
      "DOOMFIST": "",
      "GENJI": "",
      "HANZO": "",
      "JUNKRAT": "",
      "LUCIO": "",
      "MCCREE": "",
      "MEI": "",
      "MERCY": "",
      "MOIRA": "",
      "ORISA": "",
      "PHARAH": "",
      "REAPER": "counter-bad counter-strong",
      "REINHARDT": "",
      "ROADHOG": "",
      "SIGMA": "",
      "SOLDIER: 76": "",
      "SOMBRA": "counter-bad counter-medium",
      "SYMMETRA": "",
      "TORBJORN": "",
      "TRACER": "counter-bad counter-strong",
      "WIDOWMAKER": "",
      "WINSTON": "",
      "WRECKINGBALL": "",
      "ZARYA": "counter-good counter-medium",
      "ZENYATTA": "same-hero"
    }
   ]